version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file: .env.local
    restart: unless-stopped

  # Add development service for local development
  web-dev:
    build:
      context: .
      target: deps
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file: .env.local
    environment:
      - NODE_ENV=development
    # If you need to expose environment variables, create a .env file and uncomment the following line
    # env_file: .env.local